services:
  hue_exporter:
    image: ghcr.io/aexel90/hue_exporter:latest
    container_name: hue_exporter
    restart: on-failure:2
    network_mode: "host" 
    ports:
      - 9773:9773
    env_file:
      - .env