services:
  hue_exporter:
    image: hue_exporter
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure:2
    container_name: hue_exporter
    ports:
      - 9773:9773
    volumes:
      - ./hue_metrics.json:/hue_metrics.json
    env_file:
      - .env