{
 "title": "Philips Hue",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hue_brdige_info" }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hue_brdige_info" }
   ]
  },
  {
   "title": "RemoteAccess",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hue_brdige_info" }
   ]
  },
  {
   "title": "Internet",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hue_brdige_info" }
   ]
  },
  {
   "title": "Ziigbee Channel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hue_brdige_info" }
   ]
  },
  {
   "title": "API Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hue_brdige_info" }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "hue_brdige_info" }
   ]
  },
  {
   "title": "Lights ON",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(hue_light_state)" }
   ]
  },
  {
   "title": "Lights OFF",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(hue_light_state)-sum(hue_light_state)"
    }
   ]
  },
  {
   "title": "Sensor Lightlevel",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "expr": "10^((hue_sensor_lightlevel-1)/10000)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sensor Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "hue_sensor_temperature/100", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Sensor Overview",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hue_sensor_info{type=~\"ZLL.*\"}"
    }
   ]
  },
  {
   "title": "Hue Light Overview",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "hue_light_info" }
   ]
  }
 ]
}