name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build amd64 Docker image
      run: docker buildx build --platform linux/amd64 -t vremenar/hue_exporter:amd64 .
    - name: Build arm64 Docker image
      run: docker buildx build --platform ,linux/arm64 -t vremenar/hue_exporter:arm64 .
    - name: Build multi-arch Docker image
      run: docker buildx build --platform linux/amd64,linux/arm64 -t vremenar/hue_exporter:latest .
