name: Docker Image CI

env:
  REGISTRY: ghcr.io

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 22 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build amd64 Docker image
        run: docker buildx build --platform linux/amd64 -t ghcr.io/vremenar/hue_exporter/hue_exporter:latest-amd64 --push .
      - name: Build arm64 Docker image
        run: docker buildx build --platform linux/arm64 -t ghcr.io/vremenar/hue_exporter/hue_exporter:latest-arm64 --push .
      - name: Build multi-arch Docker image
        run: docker buildx build --platform "linux/amd64,linux/arm64" -t "ghcr.io/vremenar/hue_exporter/hue_exporter:latest" -t "ghcr.io/vremenar/rpi-setup/hue_exporter:latest" --push "."
