name: Create and publish a Docker image

env:
  BUILD_PLATFORM: |
    linux/arm/v7
    linux/arm64
    linux/amd64
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Tag Image
        id: tag_image
        run: |
          DOCKER_REPOSITORY=${{ env.REGISTRY }}/${{ github.repository }}
          DOCKER_REPOSITORY=$(echo $DOCKER_REPOSITORY | tr '[A-Z]' '[a-z]')
          DOCKER_TAG=latest 
          echo "docker_repository=${DOCKER_REPOSITORY}" >> $GITHUB_OUTPUT
          echo "docker_tag=${DOCKER_TAG}" >> $GITHUB_OUTPUT

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: ${{ env.BUILD_PLATFORM }}
          tags: |
            ${{ steps.tag_image.outputs.docker_repository }}:${{ steps.tag_image.outputs.docker_tag }}
            ${{ steps.tag_image.outputs.docker_repository }}:${{ github.sha }}
